trading_day: '20260131'

snapshot:
  type: "shm"
  path: "/hft_snapshot"
  is_writer: false

plugins:
  - name: WebSocket_Monitor
    library: "libmod_monitor.so"
    enabled: true
    config:
      ws_port: 8877
      pub_addr: "tcp://*:5555"
      debug: false
  
  - name: Gateway_Poll_1
    library: "libmod_gateway_poll.so"
    enabled: true
    config:
      gateway_id: "247060"
      account_id: "247060"
      cmd_shm: "/cmd_ring_247060"
      rtn_shm: "/rtn_ring_247060"
      ring_capacity: "1024"
      poll_batch: "256"
      debug: false
  
  - name: Gateway_Poll_2
    library: "libmod_gateway_poll.so"
    enabled: true
    config:
      gateway_id: "253535"
      account_id: "253535"
      cmd_shm: "/cmd_ring_253535"
      rtn_shm: "/rtn_ring_253535"
      ring_capacity: "1024"
      poll_batch: "256"
      debug: false

  - name: Gateway_Poll_3
    library: "libmod_gateway_poll.so"
    enabled: true
    config:
      gateway_id: "255028"
      account_id: "255028"
      cmd_shm: "/cmd_ring_255028"
      rtn_shm: "/rtn_ring_255028"
      ring_capacity: "1024"
      poll_batch: "256"
      debug: false
