trading_hours:
  start: "09:00:00"
  end: "23:00:00"

plugins:
  - name: Replay
    library: "../bin/libmod_replay.so"
    enabled: true
    config:
      data_file: "../data/market_data_20260130"
      interval_ms: 10

  - name: StrategyTree
    library: "../bin/libmod_strategy_tree.so"
    enabled: true
    config:
      nodes:
        - id: FACTOR_SMA
          library: "../bin/libstrat_sma.so"
          params:
            window_size: 20
            multiplier: 1000.0
            debug: false

        - id: FACTOR_IMB
          library: "../bin/libstrat_imbalance.so"
          params:
            debug: false

        - id: FACTOR_JUMP
          library: "../bin/libstrat_price_jump.so"
          params:
            threshold: 0.1
            debug: true

        - id: CS_COMBINER
          library: "../bin/libstrat_cs_combiner.so"
          params:
            debug: true
            top_pct: 0.2
            bottom_pct: 0.2
            base_volume: 1
            symbols_file: "../conf/symbols.txt"
            weights:
              SMA_Diff: 0.5
              Imbalance: 0.3
              PriceJump: 0.2

        - id: STAT_ARB_AU
          library: "../bin/libstrat_stat_arb.so"
          params:
            symbol: au2606
            window_size: 100
            sigma: 4.0
            debug: true

  - name: TradeSim
    library: "../bin/libmod_trade.so"
    enabled: true
    config: {}
